### ISSUE TITLE
Upgrade rails to ~> 7.1

### ISSUE THREAD

**Issue by heratyian** [appdev-projects/rails-7-template#26]
I'm writing a lesson on async jobs using [Solid Queue](https://github.com/basecamp/solid_queue) and [Mission Control](https://github.com/basecamp/mission_control-jobs). Mission Control requires rails ~> 7.1. Soild Queue is really nice since it uses db tables instead of redis, which makes deployments simpler/cheaper. Also, you can run it on sqlite which means you can still use codespaces. 

Any plans to upgrade the rails version?

**Comment by bpurinton** [comment]
Going to work on this soon, couple of notes to self:

> After the Rails 7.1 update, can you ensure that there are no deprecation warnings when e.g. bundle install or rails c or rails s?
> Also, it feels to me like it takes a long time to set up a codespace for the Rails 7 Template, longer than homeworks. Is that true, and if so why?
