### ISSUE TITLE
Do we want the git branch on the command line?

### ISSUE THREAD

**Issue by bpurinton** [appdev-projects/rails-7-template#5]
![image](https://user-images.githubusercontent.com/12408296/235737764-47be07e8-f4df-430a-8177-cbad0e753b05.png)

Would we like something like:

- current branch
- "dirty" marker

I find it to be nice personally, but maybe just distracting for students?

Thoughts @raghubetina @jelaniwoods?

**Comment by jelaniwoods** [comment]
We did have something similar to this for phase II projects. IIRC it sometimes got cumbersome when students created very descriptive git branch names, but that's not the end of the world. It doesn't seem particularly useful for Phase I students, assuming they won't really use branching at all.

**Comment by raghubetina** [comment]
I would like to add more content in Phase 1 around Git, especially now that we're adopting the built-in vcs in VSCode and Git Lens.

So my instinct is to keep this. Maybe they'll be branching more, in which case it might be handy. If they're still not branching much, we can drop it.

**Comment by bpurinton** [comment]
@raghubetina to be clear "keep" as in "implement"? It's not a current feature in the docker image. That screenshot is from my local dev env

**Comment by raghubetina** [comment]
Ah yes, let's add it to AD1. Or, now that it's the same image for all phases, keep it from AD2.

As to its appearance, I think we should mimic the configuration in [thoughtbot's dotfiles](https://github.com/thoughtbot/dotfiles), since that's our recommended path for local installation.

**Comment by jelaniwoods** [comment]
> As to its appearance, I think we should mimic the configuration in [thoughtbot's dotfiles](https://github.com/thoughtbot/dotfiles), since that's our recommended path for local installation.

@raghubetina from what I can tell, thoughtbot's configuration doesn't have any sort of "git dirty" marker. Is that something you think we should add?

**Comment by raghubetina** [comment]
> > As to its appearance, I think we should mimic the configuration in [thoughtbot's dotfiles](https://github.com/thoughtbot/dotfiles), since that's our recommended path for local installation.
> 
> @raghubetina from what I can tell, thoughtbot's configuration doesn't have any sort of "git dirty" marker. Is that something you think we should add?

Hm, good point. Since I use thoughtbot I guess I am not used to having that marker. Do you? Do you find it useful / do you think we should add it for students?

**Comment by jelaniwoods** [comment]
>  Do you? Do you find it useful / do you think we should add it for students?

I do have one and I find it useful for knowing if I have unstaged changes without running a command. I think it has potential to prompt students to commit more often. It might also just be annoying to them. I think there's potential, but we can always re-visit this later since the Phase I Git content is already being re-worked a lot, maybe it won't be necessary.

**Comment by raghubetina** [comment]
Hmm, good points. My instinct is to leave the dirty indicator off the command line because I already struggle with CLI real estate when e.g. typing a longer `rails g` command, and also they have tons of dirty indicators already (in the file tree, next to line numbers, etc).

**Comment by bpurinton** [comment]
From my POV as a more recent learner, having the dirty git marker definitely prompts me to commit more often. It's pretty small as well in terms of real estate. But I'm okay with waiting on this until I pull together new git workflow documentation, then we decide on the final contents of the command line prompt.

**Comment by bpurinton** [comment]
Resolved [on this PR](https://github.com/appdev-projects/rails-7-template/pull/7)
