### ISSUE TITLE
Remove firstdraft gems

### ISSUE THREAD

**Issue by bpurinton** [appdev-projects/rails-7-template#8]
@jelaniwoods Can we remove the firstdraft gems from the `Gemfile`, e.g. get rid of the `github...` from these lines:

```
gem "appdev_support", github: "firstdraft/appdev_support"
```

I actually just tried to do this, but when I `bundle`d I got 

```
Could not find gem 'appdev_support' in rubygems repository https://rubygems.org/ or installed
locally.
```

So maybe this change isn't quite ready yet?

**Comment by jelaniwoods** [comment]
Resolved in https://github.com/appdev-projects/rails-7-template/commit/99b07c33faa09ae31745f968a682b4e56e6bff7c
